##version: '3.8'
services:
  
  # DJANGO - GUNICORN
  backend:
    build:
      context: ./dfrm_be
      dockerfile: Dockerfile.prod
    container_name: dfrm_be
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    expose:
      - "8000"

  # NGINX REVERSE PROXY
  nginx_proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    depends_on:
      - backend
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map the local Nginx config to the container
      - letsencrypt:/etc/letsencrypt # persist SSL certificate across restarts
#     networks:
#       - dfrm_network # connect to a custom Docker network for isolation and communication

volumes:
  letsencrypt:

# networks:
#   dfrm_network:
#     driver: bridge # use the default bridge network driver
