# Dockerfile for Nginx
FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY 500.html /etc/nginx/500.html

# install certbot and set up cron job for auto-renewal
RUN apk update && \
    apk add certbot certbot-nginx openssl && \
    echo "0 0,12 * * * certbot renew --nginx" > /etc/crontabs/root 

# copy script that runs both crond and nginx
COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 80

CMD ["/start.sh"]