# Dockerfile for Nginx
FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY 500.html /etc/nginx/500.html

# install certbot and set up cron job for auto-renewal
RUN apk update && \
    apk add certbot certbot-nginx openssl && \
    echo "0 0,12 * * * certbot renew --nginx" > /etc/crontabs/root && \
    crontab /etc/crontabs/root

EXPOSE 80

CMD ["crond", "-f", "&", "nginx", "-g", "daemon off;"]