##version: '3.8'
services:
  
  # DJANGO - GUNICORN
  backend:
    build:
      context: ./dfrm_be
      dockerfile: Dockerfile.prod
    container_name: dfrm_be
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    expose:
      - "8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Limit each log file to 10 MB
        max-file: "3"   # Keep up to 3 log files

  # NGINX REVERSE PROXY
  nginx_proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    depends_on:
      - backend
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map the local Nginx config to the container
      - letsencrypt:/etc/letsencrypt # persist SSL certificate across restarts
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  letsencrypt: